# Generated by Django 3.2.6 on 2021-08-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=10)),
                ('shares', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
