# Generated by Django 3.2.6 on 2021-08-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SockList',
            new_name='StockList',
        ),
    ]
